### ISSUE TITLE
Manifest needs update to avoid deprecation

### ISSUE THREAD

**Issue by balupton** [browserstate/historyjsit.crx#1]
Received this email:

---

Greetings, Chrome Extension developer! Our records indicate that your Chrome Web Store extension, "History.js It!", with ID: oikegcanmmpmcmbkdopcfdlbiepmcebg is still using version 1 (V1) of the manifest file format. 

We are sending you this email to remind you that starting in two weeks all extensions that use the v1 manifest file format will no longer be visible in the Chrome Web Store wall pages, search results or category pages. Users will still be able to access and install your extension if they have a direct link to the listing, and existing users of your extension will not be affected. However, it’s likely that you will see a significant drop in new users unless you take further action. Later in the year, we will take further steps to deprecate extensions based on the manifest file support schedule we published earlier this year.

Please take a moment to update your extensions to use manifest version 2 to avoid any interruptions in your store presence. If you have already updated your items to use manifest V2, you can disregard this message. If you need further assistance, you can follow the manifest V2 tutorial, or contact us in the chromium-extensions forum.

Please do not reply to this email - the response is not monitored.

With Best Regards,
The Chrome Web Store Team

**Comment by balupton** [comment]
Fixed with v1.1.0

**Comment by PwnicornDev** [comment]
So obviously #2 is a result of this, as inline script is forbidden as per manifest V2.
